apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: indicators-api-app
  name: indicators-api-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: indicators-api-app
  strategy: {}
  template:
    metadata:
      labels:
        app: indicators-api-app
    spec:
      containers:
        - image: indicatorsservice.azurecr.io/dconchamzindicatorsapitest:##BUILD_ID##
          name: webapp
          imagePullPolicy: Always
          resources: {}
          ports:
            - containerPort: 3000
      restartPolicy: Always
